#!/usr/bin/python3
import io, sys
import qrcode

url = str(sys.argv[1])
qr = qrcode.QRCode()
qr.add_data(url)
f = io.StringIO()
qr.print_ascii(out=f)
f.seek(0)
print(f.read())
print('Escanee el codigo QR con su telefono movil!')
